"""update is_deleted field

Revision ID: 7ddcb5ab5234
Revises: 
Create Date: 2026-02-11 15:03:06.879155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ddcb5ab5234'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes') as batch_op:
        batch_op.alter_column('is_deleted',
                existing_type=sa.BOOLEAN(),
                nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes') as batch_op:
        batch_op.alter_column('is_deleted',
                existing_type=sa.BOOLEAN(),
                nullable=True)
    # ### end Alembic commands ###
